import {Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navber/Navbar";
import Footer from "./components/Footer/Footer";
import {Toaster} from "react-hot-toast";
import {AuthProvider} from "@/context/AuthProvider/AuthProvider";
import {ReduxProvider} from "@/provider/ReduxProvider";

const inter = Poppins({subsets: ["latin"], weight: "400"});

export const metadata = {
    title: "Snugstaff",
    description: "Generated by Snugstaff",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Toaster position="top-right" />
                <ReduxProvider>
                    <AuthProvider>
                        <Navbar />
                        {children}
                        <Footer />
                    </AuthProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
